#!/bin/bash

# This script runs the SAT solver program on a provided .cnf file or all .cnf files in the 'input' directory.

make >/dev/null 2>&1 || { echo "Make failed. Exiting."; exit 1; }

if [ "$#" -eq 1 ]; then
  FILE="$1"
elif [ "$#" -eq 0 ]; then
  DIR="input"
else
  echo "Usage: $0 [<filename>]"
  echo "<filename>: Path to the input file"
  exit 1
fi

if [ -n "$FILE" ]; then
  if [ -f "$FILE" ]; then
    ./bin/sat-solver "$FILE"
  else
    echo "Error: File '$FILE' not found."
    exit 1
  fi

elif [ -n "$DIR" ]; then
  if [ -d "$DIR" ]; then
    find "$DIR" -type f -name "*.cnf" -exec ./bin/sat-solver {} \;
  else
    echo "Error: Directory '$DIR' not found."
    exit 1
  fi
else 
  echo "Unexpected error."
  exit 1
fi
